language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
env:
  global:
    - BINTRAY_USER=lembrd
    - secure: lKu1k+6tb8wvrrzpNcQw8VTY8Rv2E9uVItQcWhwSkkt8r56dZS3yjAh/UBTgOiM965VFrpP+11IW9gFn5B3JTt4zjF5T3fWxBCLzhMGnRHHpB0vvR6k6dMCmW9ZCQKU+oANCZvATcJF9TaF5EjLMrCDqMHqJSvY9bVnOkNDyenKU8Y97z5JOrx5FUufafxTeK7cVyQ5/LzTmUfJ+TM/gLpUUWYuQb0Lxs0Vk+1DcwhJP3O+B8wxPxZQ1VzE7PX32IuRnEEuCz6DtDZtwEmp7194rpmnFfhVfwoholnE+6usDMNXrXbdy4i3MRGbehGRGsr4PgAF/7XAbRUF3tHmeS/0xrnYu4+cpl27eJhBf33EMpCoWq6VabFo/l6+9uci1Q6+I8XT7W7jQdjRMAh7y+xVt9IctORo+Dv3lSI1BMpYBOjjhECOIHuXHjLLm7gn4LxYJG0dtQlXDsp5EbO73NOpUGZsDBw3Var1VIrWybolDM6wBLLw+tBGhcxS2rQnf+UYl81dsoYHjZXp7x3I2mUCQoQ3oLg4DQxG4+4JHxML4JkCS0ypW703/ouqnljsfj/v3md2Pe+/8gwyZ6qrF2GCt+A2BPsU1UoL0QV4mH7CmrxocYWzEVAaygKhuV7NravZSWqUtBEkgg/hVOfEppvNlJhG2Gyum0OBdjO66Ugw=
script:
- sh "$TRAVIS_BUILD_DIR/travis/travis-bintray-credentials.sh"
- sbt publish
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.m2"
  - "$HOME/.sbt"
